/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "./stencil-public-runtime";
import { Theme } from "./globalHelpers";
import { NotificationItem } from "./components/cm-notification-container/cm-notification-container";
import { State } from "./components/cm-page/cm-page";
export namespace Components {
    interface CmBanner {
    }
    interface CmButton {
        "appearance": 'main' | 'primary' | 'secondary' | 'danger' | 'link';
        "disabled": boolean;
        "label": string;
    }
    interface CmCheckbox {
        "checked": boolean;
        "disabled": boolean;
        "indeterminate": boolean;
        "label": string;
    }
    interface CmContext {
        "getResolvedTheme": () => Promise<Theme>;
        "theme": Theme | 'Automatic';
    }
    interface CmDatalist {
        "headline": string;
    }
    interface CmDatalistItem {
        "label": string;
    }
    interface CmFooter {
        "text": string;
    }
    interface CmHeader {
    }
    interface CmIcon {
        "icon": | 'contextMenu'
		| 'close'
		| 'closeLarge'
		| 'search'
		| 'help'
		| 'information'
		| 'sort'
		| 'plus'
		| 'minus'
		| 'copy'
		| 'show'
		| 'hide'
		| 'edit'
		| 'delete'
		| 'up'
		| 'down'
		| 'left'
		| 'right';
        "theme": Theme;
    }
    interface CmIconButton {
        "disabled": boolean;
        "icon": | 'contextMenu'
		| 'close'
		| 'closeLarge'
		| 'search'
		| 'help'
		| 'information'
		| 'sort'
		| 'plus'
		| 'minus'
		| 'copy'
		| 'show'
		| 'hide'
		| 'edit'
		| 'delete'
		| 'up'
		| 'down'
		| 'left'
		| 'right';
    }
    interface CmLink {
        "href": string;
        "label": string;
        "openIn": 'sameTab' | 'newTab';
    }
    interface CmLoader {
        "size": 'small' | 'normal';
    }
    interface CmLogo {
    }
    interface CmModal {
        "headline": string;
        "open": () => Promise<"confirm" | "cancel">;
        "position": 'top' | 'center';
    }
    interface CmNotification {
        "appearance": 'success' | 'error' | 'info';
        "description": string;
        "dismiss": () => Promise<void>;
        "headline": string;
        "isBeingHovered": () => Promise<boolean>;
        "navigationLabel": string;
        "userDismissable": boolean;
    }
    interface CmNotificationContainer {
        "enqueueNotification": (notification: NotificationItem) => Promise<{ hasBeenShown(): boolean; remove(): void; }>;
    }
    interface CmPage {
        "activeLabel": string;
        /**
          * Returns the currently active tab, handle, and title.
         */
        "getActiveState": () => Promise<State>;
        /**
          * Switches to a tab based on their label.
          * @param label Title of the target tab.
         */
        "switchToTab": (label: string) => Promise<void>;
        /**
          * Switches to a tab based on their index.
          * @param index Index of the target tab.
         */
        "switchToTabIndex": (index: number) => Promise<void>;
    }
    interface CmPageTab {
        "active": boolean;
        "label": string;
    }
    interface CmPageTabHandle {
        "active": boolean;
        "label": string;
    }
    interface CmSelect {
        "disabled": boolean;
        "options": Array<{
		label: string
		value: string
	}>;
    }
    interface CmText {
    }
    interface CmToggle {
        "checked": boolean;
        "disabled": boolean;
        "label": string;
    }
}
declare global {
    interface HTMLCmBannerElement extends Components.CmBanner, HTMLStencilElement {
    }
    var HTMLCmBannerElement: {
        prototype: HTMLCmBannerElement;
        new (): HTMLCmBannerElement;
    };
    interface HTMLCmButtonElement extends Components.CmButton, HTMLStencilElement {
    }
    var HTMLCmButtonElement: {
        prototype: HTMLCmButtonElement;
        new (): HTMLCmButtonElement;
    };
    interface HTMLCmCheckboxElement extends Components.CmCheckbox, HTMLStencilElement {
    }
    var HTMLCmCheckboxElement: {
        prototype: HTMLCmCheckboxElement;
        new (): HTMLCmCheckboxElement;
    };
    interface HTMLCmContextElement extends Components.CmContext, HTMLStencilElement {
    }
    var HTMLCmContextElement: {
        prototype: HTMLCmContextElement;
        new (): HTMLCmContextElement;
    };
    interface HTMLCmDatalistElement extends Components.CmDatalist, HTMLStencilElement {
    }
    var HTMLCmDatalistElement: {
        prototype: HTMLCmDatalistElement;
        new (): HTMLCmDatalistElement;
    };
    interface HTMLCmDatalistItemElement extends Components.CmDatalistItem, HTMLStencilElement {
    }
    var HTMLCmDatalistItemElement: {
        prototype: HTMLCmDatalistItemElement;
        new (): HTMLCmDatalistItemElement;
    };
    interface HTMLCmFooterElement extends Components.CmFooter, HTMLStencilElement {
    }
    var HTMLCmFooterElement: {
        prototype: HTMLCmFooterElement;
        new (): HTMLCmFooterElement;
    };
    interface HTMLCmHeaderElement extends Components.CmHeader, HTMLStencilElement {
    }
    var HTMLCmHeaderElement: {
        prototype: HTMLCmHeaderElement;
        new (): HTMLCmHeaderElement;
    };
    interface HTMLCmIconElement extends Components.CmIcon, HTMLStencilElement {
    }
    var HTMLCmIconElement: {
        prototype: HTMLCmIconElement;
        new (): HTMLCmIconElement;
    };
    interface HTMLCmIconButtonElement extends Components.CmIconButton, HTMLStencilElement {
    }
    var HTMLCmIconButtonElement: {
        prototype: HTMLCmIconButtonElement;
        new (): HTMLCmIconButtonElement;
    };
    interface HTMLCmLinkElement extends Components.CmLink, HTMLStencilElement {
    }
    var HTMLCmLinkElement: {
        prototype: HTMLCmLinkElement;
        new (): HTMLCmLinkElement;
    };
    interface HTMLCmLoaderElement extends Components.CmLoader, HTMLStencilElement {
    }
    var HTMLCmLoaderElement: {
        prototype: HTMLCmLoaderElement;
        new (): HTMLCmLoaderElement;
    };
    interface HTMLCmLogoElement extends Components.CmLogo, HTMLStencilElement {
    }
    var HTMLCmLogoElement: {
        prototype: HTMLCmLogoElement;
        new (): HTMLCmLogoElement;
    };
    interface HTMLCmModalElement extends Components.CmModal, HTMLStencilElement {
    }
    var HTMLCmModalElement: {
        prototype: HTMLCmModalElement;
        new (): HTMLCmModalElement;
    };
    interface HTMLCmNotificationElement extends Components.CmNotification, HTMLStencilElement {
    }
    var HTMLCmNotificationElement: {
        prototype: HTMLCmNotificationElement;
        new (): HTMLCmNotificationElement;
    };
    interface HTMLCmNotificationContainerElement extends Components.CmNotificationContainer, HTMLStencilElement {
    }
    var HTMLCmNotificationContainerElement: {
        prototype: HTMLCmNotificationContainerElement;
        new (): HTMLCmNotificationContainerElement;
    };
    interface HTMLCmPageElement extends Components.CmPage, HTMLStencilElement {
    }
    var HTMLCmPageElement: {
        prototype: HTMLCmPageElement;
        new (): HTMLCmPageElement;
    };
    interface HTMLCmPageTabElement extends Components.CmPageTab, HTMLStencilElement {
    }
    var HTMLCmPageTabElement: {
        prototype: HTMLCmPageTabElement;
        new (): HTMLCmPageTabElement;
    };
    interface HTMLCmPageTabHandleElement extends Components.CmPageTabHandle, HTMLStencilElement {
    }
    var HTMLCmPageTabHandleElement: {
        prototype: HTMLCmPageTabHandleElement;
        new (): HTMLCmPageTabHandleElement;
    };
    interface HTMLCmSelectElement extends Components.CmSelect, HTMLStencilElement {
    }
    var HTMLCmSelectElement: {
        prototype: HTMLCmSelectElement;
        new (): HTMLCmSelectElement;
    };
    interface HTMLCmTextElement extends Components.CmText, HTMLStencilElement {
    }
    var HTMLCmTextElement: {
        prototype: HTMLCmTextElement;
        new (): HTMLCmTextElement;
    };
    interface HTMLCmToggleElement extends Components.CmToggle, HTMLStencilElement {
    }
    var HTMLCmToggleElement: {
        prototype: HTMLCmToggleElement;
        new (): HTMLCmToggleElement;
    };
    interface HTMLElementTagNameMap {
        "cm-banner": HTMLCmBannerElement;
        "cm-button": HTMLCmButtonElement;
        "cm-checkbox": HTMLCmCheckboxElement;
        "cm-context": HTMLCmContextElement;
        "cm-datalist": HTMLCmDatalistElement;
        "cm-datalist-item": HTMLCmDatalistItemElement;
        "cm-footer": HTMLCmFooterElement;
        "cm-header": HTMLCmHeaderElement;
        "cm-icon": HTMLCmIconElement;
        "cm-icon-button": HTMLCmIconButtonElement;
        "cm-link": HTMLCmLinkElement;
        "cm-loader": HTMLCmLoaderElement;
        "cm-logo": HTMLCmLogoElement;
        "cm-modal": HTMLCmModalElement;
        "cm-notification": HTMLCmNotificationElement;
        "cm-notification-container": HTMLCmNotificationContainerElement;
        "cm-page": HTMLCmPageElement;
        "cm-page-tab": HTMLCmPageTabElement;
        "cm-page-tab-handle": HTMLCmPageTabHandleElement;
        "cm-select": HTMLCmSelectElement;
        "cm-text": HTMLCmTextElement;
        "cm-toggle": HTMLCmToggleElement;
    }
}
declare namespace LocalJSX {
    interface CmBanner {
    }
    interface CmButton {
        "appearance"?: 'main' | 'primary' | 'secondary' | 'danger' | 'link';
        "disabled"?: boolean;
        "label"?: string;
        "onCmPress"?: (event: CustomEvent<{}>) => void;
    }
    interface CmCheckbox {
        "checked"?: boolean;
        "disabled"?: boolean;
        "indeterminate"?: boolean;
        "label"?: string;
        "onCmInput"?: (event: CustomEvent<{ isChecked: boolean }>) => void;
    }
    interface CmContext {
        "onThemeChanged"?: (event: CustomEvent<{ theme: Theme }>) => void;
        "theme"?: Theme | 'Automatic';
    }
    interface CmDatalist {
        "headline"?: string;
    }
    interface CmDatalistItem {
        "label"?: string;
    }
    interface CmFooter {
        "text"?: string;
    }
    interface CmHeader {
    }
    interface CmIcon {
        "icon"?: | 'contextMenu'
		| 'close'
		| 'closeLarge'
		| 'search'
		| 'help'
		| 'information'
		| 'sort'
		| 'plus'
		| 'minus'
		| 'copy'
		| 'show'
		| 'hide'
		| 'edit'
		| 'delete'
		| 'up'
		| 'down'
		| 'left'
		| 'right';
        "theme"?: Theme;
    }
    interface CmIconButton {
        "disabled"?: boolean;
        "icon"?: | 'contextMenu'
		| 'close'
		| 'closeLarge'
		| 'search'
		| 'help'
		| 'information'
		| 'sort'
		| 'plus'
		| 'minus'
		| 'copy'
		| 'show'
		| 'hide'
		| 'edit'
		| 'delete'
		| 'up'
		| 'down'
		| 'left'
		| 'right';
        "onCmPress"?: (event: CustomEvent<{}>) => void;
    }
    interface CmLink {
        "href"?: string;
        "label"?: string;
        "openIn"?: 'sameTab' | 'newTab';
    }
    interface CmLoader {
        "size"?: 'small' | 'normal';
    }
    interface CmLogo {
    }
    interface CmModal {
        "headline"?: string;
        "position"?: 'top' | 'center';
    }
    interface CmNotification {
        "appearance"?: 'success' | 'error' | 'info';
        "description"?: string;
        "headline"?: string;
        "navigationLabel"?: string;
        "onCmDismissed"?: (event: CustomEvent<{}>) => void;
        "onCmNotificationNavigation"?: (event: CustomEvent<{}>) => void;
        "onDidLoad"?: (event: CustomEvent<{}>) => void;
        "userDismissable"?: boolean;
    }
    interface CmNotificationContainer {
    }
    interface CmPage {
        "activeLabel"?: string;
        /**
          * This is emitted when the active tab is changed.
         */
        "onTabChanged"?: (event: CustomEvent<State>) => void;
    }
    interface CmPageTab {
        "active"?: boolean;
        "label"?: string;
        "onTabModified"?: (event: CustomEvent<any>) => void;
    }
    interface CmPageTabHandle {
        "active"?: boolean;
        "label"?: string;
        "onUserSelectedTab"?: (event: CustomEvent<{
		originalEvent: MouseEvent | KeyboardEvent
		handle: HTMLCmPageTabHandleElement
		label: string
	}>) => void;
    }
    interface CmSelect {
        "disabled"?: boolean;
        "onCmInput"?: (event: CustomEvent<{ newValue: string }>) => void;
        "options"?: Array<{
		label: string
		value: string
	}>;
    }
    interface CmText {
    }
    interface CmToggle {
        "checked"?: boolean;
        "disabled"?: boolean;
        "label"?: string;
        "onCmInput"?: (event: CustomEvent<{ isChecked: boolean }>) => void;
    }
    interface IntrinsicElements {
        "cm-banner": CmBanner;
        "cm-button": CmButton;
        "cm-checkbox": CmCheckbox;
        "cm-context": CmContext;
        "cm-datalist": CmDatalist;
        "cm-datalist-item": CmDatalistItem;
        "cm-footer": CmFooter;
        "cm-header": CmHeader;
        "cm-icon": CmIcon;
        "cm-icon-button": CmIconButton;
        "cm-link": CmLink;
        "cm-loader": CmLoader;
        "cm-logo": CmLogo;
        "cm-modal": CmModal;
        "cm-notification": CmNotification;
        "cm-notification-container": CmNotificationContainer;
        "cm-page": CmPage;
        "cm-page-tab": CmPageTab;
        "cm-page-tab-handle": CmPageTabHandle;
        "cm-select": CmSelect;
        "cm-text": CmText;
        "cm-toggle": CmToggle;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "cm-banner": LocalJSX.CmBanner & JSXBase.HTMLAttributes<HTMLCmBannerElement>;
            "cm-button": LocalJSX.CmButton & JSXBase.HTMLAttributes<HTMLCmButtonElement>;
            "cm-checkbox": LocalJSX.CmCheckbox & JSXBase.HTMLAttributes<HTMLCmCheckboxElement>;
            "cm-context": LocalJSX.CmContext & JSXBase.HTMLAttributes<HTMLCmContextElement>;
            "cm-datalist": LocalJSX.CmDatalist & JSXBase.HTMLAttributes<HTMLCmDatalistElement>;
            "cm-datalist-item": LocalJSX.CmDatalistItem & JSXBase.HTMLAttributes<HTMLCmDatalistItemElement>;
            "cm-footer": LocalJSX.CmFooter & JSXBase.HTMLAttributes<HTMLCmFooterElement>;
            "cm-header": LocalJSX.CmHeader & JSXBase.HTMLAttributes<HTMLCmHeaderElement>;
            "cm-icon": LocalJSX.CmIcon & JSXBase.HTMLAttributes<HTMLCmIconElement>;
            "cm-icon-button": LocalJSX.CmIconButton & JSXBase.HTMLAttributes<HTMLCmIconButtonElement>;
            "cm-link": LocalJSX.CmLink & JSXBase.HTMLAttributes<HTMLCmLinkElement>;
            "cm-loader": LocalJSX.CmLoader & JSXBase.HTMLAttributes<HTMLCmLoaderElement>;
            "cm-logo": LocalJSX.CmLogo & JSXBase.HTMLAttributes<HTMLCmLogoElement>;
            "cm-modal": LocalJSX.CmModal & JSXBase.HTMLAttributes<HTMLCmModalElement>;
            "cm-notification": LocalJSX.CmNotification & JSXBase.HTMLAttributes<HTMLCmNotificationElement>;
            "cm-notification-container": LocalJSX.CmNotificationContainer & JSXBase.HTMLAttributes<HTMLCmNotificationContainerElement>;
            "cm-page": LocalJSX.CmPage & JSXBase.HTMLAttributes<HTMLCmPageElement>;
            "cm-page-tab": LocalJSX.CmPageTab & JSXBase.HTMLAttributes<HTMLCmPageTabElement>;
            "cm-page-tab-handle": LocalJSX.CmPageTabHandle & JSXBase.HTMLAttributes<HTMLCmPageTabHandleElement>;
            "cm-select": LocalJSX.CmSelect & JSXBase.HTMLAttributes<HTMLCmSelectElement>;
            "cm-text": LocalJSX.CmText & JSXBase.HTMLAttributes<HTMLCmTextElement>;
            "cm-toggle": LocalJSX.CmToggle & JSXBase.HTMLAttributes<HTMLCmToggleElement>;
        }
    }
}
