/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface CmButton {
        "appearance": "main" | "primary" | "secondary" | "danger";
        "disabled": boolean;
        "label": string;
    }
    interface CmLink {
        "href": string;
        "label": string;
        "openIn": "sameTab" | "newTab";
    }
    interface CmText {
    }
}
declare global {
    interface HTMLCmButtonElement extends Components.CmButton, HTMLStencilElement {
    }
    var HTMLCmButtonElement: {
        prototype: HTMLCmButtonElement;
        new (): HTMLCmButtonElement;
    };
    interface HTMLCmLinkElement extends Components.CmLink, HTMLStencilElement {
    }
    var HTMLCmLinkElement: {
        prototype: HTMLCmLinkElement;
        new (): HTMLCmLinkElement;
    };
    interface HTMLCmTextElement extends Components.CmText, HTMLStencilElement {
    }
    var HTMLCmTextElement: {
        prototype: HTMLCmTextElement;
        new (): HTMLCmTextElement;
    };
    interface HTMLElementTagNameMap {
        "cm-button": HTMLCmButtonElement;
        "cm-link": HTMLCmLinkElement;
        "cm-text": HTMLCmTextElement;
    }
}
declare namespace LocalJSX {
    interface CmButton {
        "appearance"?: "main" | "primary" | "secondary" | "danger";
        "disabled"?: boolean;
        "label"?: string;
        "onCmPress"?: (event: CustomEvent<{}>) => void;
    }
    interface CmLink {
        "href"?: string;
        "label"?: string;
        "openIn"?: "sameTab" | "newTab";
    }
    interface CmText {
    }
    interface IntrinsicElements {
        "cm-button": CmButton;
        "cm-link": CmLink;
        "cm-text": CmText;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "cm-button": LocalJSX.CmButton & JSXBase.HTMLAttributes<HTMLCmButtonElement>;
            "cm-link": LocalJSX.CmLink & JSXBase.HTMLAttributes<HTMLCmLinkElement>;
            "cm-text": LocalJSX.CmText & JSXBase.HTMLAttributes<HTMLCmTextElement>;
        }
    }
}
