/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { State } from "./components/cm-page/cm-page";
export namespace Components {
    interface CmButton {
        "appearance": 'main' | 'primary' | 'secondary' | 'danger';
        "disabled": boolean;
        "label": string;
    }
    interface CmDatalist {
        "headline": string;
    }
    interface CmDatalistItem {
        "label": string;
    }
    interface CmFooter {
        "text": string;
    }
    interface CmHeader {
    }
    interface CmIcon {
        "icon": | 'contextMenu'
		| 'close'
		| 'closeLarge'
		| 'search'
		| 'help'
		| 'information'
		| 'sort'
		| 'plus'
		| 'minus'
		| 'copy'
		| 'show'
		| 'hide'
		| 'edit'
		| 'delete'
		| 'up'
		| 'down'
		| 'left'
		| 'right';
    }
    interface CmIconButton {
        "disabled": boolean;
        "icon": | 'contextMenu'
		| 'close'
		| 'closeLarge'
		| 'search'
		| 'help'
		| 'information'
		| 'sort'
		| 'plus'
		| 'minus'
		| 'copy'
		| 'show'
		| 'hide'
		| 'edit'
		| 'delete'
		| 'up'
		| 'down'
		| 'left'
		| 'right';
    }
    interface CmLink {
        "href": string;
        "label": string;
        "openIn": 'sameTab' | 'newTab';
    }
    interface CmLoader {
        "size": 'small' | 'normal';
    }
    interface CmLogo {
    }
    interface CmModal {
        "headline": string;
        "open": () => Promise<"confirm" | "cancel">;
        "position": 'top' | 'center';
    }
    interface CmPage {
        "activeLabel": string;
        /**
          * Returns the currently active tab, handle, and title.
         */
        "getActiveState": () => Promise<State>;
        /**
          * Switches to a tab based on their label.
          * @param label Title of the target tab.
         */
        "switchToTab": (label: string) => Promise<void>;
        /**
          * Switches to a tab based on their index.
          * @param index Index of the target tab.
         */
        "switchToTabIndex": (index: number) => Promise<void>;
    }
    interface CmPageTab {
        "active": boolean;
        "label": string;
    }
    interface CmPageTabHandle {
        "active": boolean;
        "label": string;
    }
    interface CmText {
    }
}
declare global {
    interface HTMLCmButtonElement extends Components.CmButton, HTMLStencilElement {
    }
    var HTMLCmButtonElement: {
        prototype: HTMLCmButtonElement;
        new (): HTMLCmButtonElement;
    };
    interface HTMLCmDatalistElement extends Components.CmDatalist, HTMLStencilElement {
    }
    var HTMLCmDatalistElement: {
        prototype: HTMLCmDatalistElement;
        new (): HTMLCmDatalistElement;
    };
    interface HTMLCmDatalistItemElement extends Components.CmDatalistItem, HTMLStencilElement {
    }
    var HTMLCmDatalistItemElement: {
        prototype: HTMLCmDatalistItemElement;
        new (): HTMLCmDatalistItemElement;
    };
    interface HTMLCmFooterElement extends Components.CmFooter, HTMLStencilElement {
    }
    var HTMLCmFooterElement: {
        prototype: HTMLCmFooterElement;
        new (): HTMLCmFooterElement;
    };
    interface HTMLCmHeaderElement extends Components.CmHeader, HTMLStencilElement {
    }
    var HTMLCmHeaderElement: {
        prototype: HTMLCmHeaderElement;
        new (): HTMLCmHeaderElement;
    };
    interface HTMLCmIconElement extends Components.CmIcon, HTMLStencilElement {
    }
    var HTMLCmIconElement: {
        prototype: HTMLCmIconElement;
        new (): HTMLCmIconElement;
    };
    interface HTMLCmIconButtonElement extends Components.CmIconButton, HTMLStencilElement {
    }
    var HTMLCmIconButtonElement: {
        prototype: HTMLCmIconButtonElement;
        new (): HTMLCmIconButtonElement;
    };
    interface HTMLCmLinkElement extends Components.CmLink, HTMLStencilElement {
    }
    var HTMLCmLinkElement: {
        prototype: HTMLCmLinkElement;
        new (): HTMLCmLinkElement;
    };
    interface HTMLCmLoaderElement extends Components.CmLoader, HTMLStencilElement {
    }
    var HTMLCmLoaderElement: {
        prototype: HTMLCmLoaderElement;
        new (): HTMLCmLoaderElement;
    };
    interface HTMLCmLogoElement extends Components.CmLogo, HTMLStencilElement {
    }
    var HTMLCmLogoElement: {
        prototype: HTMLCmLogoElement;
        new (): HTMLCmLogoElement;
    };
    interface HTMLCmModalElement extends Components.CmModal, HTMLStencilElement {
    }
    var HTMLCmModalElement: {
        prototype: HTMLCmModalElement;
        new (): HTMLCmModalElement;
    };
    interface HTMLCmPageElement extends Components.CmPage, HTMLStencilElement {
    }
    var HTMLCmPageElement: {
        prototype: HTMLCmPageElement;
        new (): HTMLCmPageElement;
    };
    interface HTMLCmPageTabElement extends Components.CmPageTab, HTMLStencilElement {
    }
    var HTMLCmPageTabElement: {
        prototype: HTMLCmPageTabElement;
        new (): HTMLCmPageTabElement;
    };
    interface HTMLCmPageTabHandleElement extends Components.CmPageTabHandle, HTMLStencilElement {
    }
    var HTMLCmPageTabHandleElement: {
        prototype: HTMLCmPageTabHandleElement;
        new (): HTMLCmPageTabHandleElement;
    };
    interface HTMLCmTextElement extends Components.CmText, HTMLStencilElement {
    }
    var HTMLCmTextElement: {
        prototype: HTMLCmTextElement;
        new (): HTMLCmTextElement;
    };
    interface HTMLElementTagNameMap {
        "cm-button": HTMLCmButtonElement;
        "cm-datalist": HTMLCmDatalistElement;
        "cm-datalist-item": HTMLCmDatalistItemElement;
        "cm-footer": HTMLCmFooterElement;
        "cm-header": HTMLCmHeaderElement;
        "cm-icon": HTMLCmIconElement;
        "cm-icon-button": HTMLCmIconButtonElement;
        "cm-link": HTMLCmLinkElement;
        "cm-loader": HTMLCmLoaderElement;
        "cm-logo": HTMLCmLogoElement;
        "cm-modal": HTMLCmModalElement;
        "cm-page": HTMLCmPageElement;
        "cm-page-tab": HTMLCmPageTabElement;
        "cm-page-tab-handle": HTMLCmPageTabHandleElement;
        "cm-text": HTMLCmTextElement;
    }
}
declare namespace LocalJSX {
    interface CmButton {
        "appearance"?: 'main' | 'primary' | 'secondary' | 'danger';
        "disabled"?: boolean;
        "label"?: string;
        "onCmPress"?: (event: CustomEvent<{}>) => void;
    }
    interface CmDatalist {
        "headline"?: string;
    }
    interface CmDatalistItem {
        "label"?: string;
    }
    interface CmFooter {
        "text"?: string;
    }
    interface CmHeader {
    }
    interface CmIcon {
        "icon"?: | 'contextMenu'
		| 'close'
		| 'closeLarge'
		| 'search'
		| 'help'
		| 'information'
		| 'sort'
		| 'plus'
		| 'minus'
		| 'copy'
		| 'show'
		| 'hide'
		| 'edit'
		| 'delete'
		| 'up'
		| 'down'
		| 'left'
		| 'right';
    }
    interface CmIconButton {
        "disabled"?: boolean;
        "icon"?: | 'contextMenu'
		| 'close'
		| 'closeLarge'
		| 'search'
		| 'help'
		| 'information'
		| 'sort'
		| 'plus'
		| 'minus'
		| 'copy'
		| 'show'
		| 'hide'
		| 'edit'
		| 'delete'
		| 'up'
		| 'down'
		| 'left'
		| 'right';
        "onCmPress"?: (event: CustomEvent<{}>) => void;
    }
    interface CmLink {
        "href"?: string;
        "label"?: string;
        "openIn"?: 'sameTab' | 'newTab';
    }
    interface CmLoader {
        "size"?: 'small' | 'normal';
    }
    interface CmLogo {
    }
    interface CmModal {
        "headline"?: string;
        "position"?: 'top' | 'center';
    }
    interface CmPage {
        "activeLabel"?: string;
        /**
          * This is emitted when the active tab is changed.
         */
        "onTabChanged"?: (event: CustomEvent<State>) => void;
    }
    interface CmPageTab {
        "active"?: boolean;
        "label"?: string;
        "onTabModified"?: (event: CustomEvent<any>) => void;
    }
    interface CmPageTabHandle {
        "active"?: boolean;
        "label"?: string;
        "onUserSelectedTab"?: (event: CustomEvent<{
		originalEvent: MouseEvent | KeyboardEvent
		handle: HTMLCmPageTabHandleElement
		label: string
	}>) => void;
    }
    interface CmText {
    }
    interface IntrinsicElements {
        "cm-button": CmButton;
        "cm-datalist": CmDatalist;
        "cm-datalist-item": CmDatalistItem;
        "cm-footer": CmFooter;
        "cm-header": CmHeader;
        "cm-icon": CmIcon;
        "cm-icon-button": CmIconButton;
        "cm-link": CmLink;
        "cm-loader": CmLoader;
        "cm-logo": CmLogo;
        "cm-modal": CmModal;
        "cm-page": CmPage;
        "cm-page-tab": CmPageTab;
        "cm-page-tab-handle": CmPageTabHandle;
        "cm-text": CmText;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "cm-button": LocalJSX.CmButton & JSXBase.HTMLAttributes<HTMLCmButtonElement>;
            "cm-datalist": LocalJSX.CmDatalist & JSXBase.HTMLAttributes<HTMLCmDatalistElement>;
            "cm-datalist-item": LocalJSX.CmDatalistItem & JSXBase.HTMLAttributes<HTMLCmDatalistItemElement>;
            "cm-footer": LocalJSX.CmFooter & JSXBase.HTMLAttributes<HTMLCmFooterElement>;
            "cm-header": LocalJSX.CmHeader & JSXBase.HTMLAttributes<HTMLCmHeaderElement>;
            "cm-icon": LocalJSX.CmIcon & JSXBase.HTMLAttributes<HTMLCmIconElement>;
            "cm-icon-button": LocalJSX.CmIconButton & JSXBase.HTMLAttributes<HTMLCmIconButtonElement>;
            "cm-link": LocalJSX.CmLink & JSXBase.HTMLAttributes<HTMLCmLinkElement>;
            "cm-loader": LocalJSX.CmLoader & JSXBase.HTMLAttributes<HTMLCmLoaderElement>;
            "cm-logo": LocalJSX.CmLogo & JSXBase.HTMLAttributes<HTMLCmLogoElement>;
            "cm-modal": LocalJSX.CmModal & JSXBase.HTMLAttributes<HTMLCmModalElement>;
            "cm-page": LocalJSX.CmPage & JSXBase.HTMLAttributes<HTMLCmPageElement>;
            "cm-page-tab": LocalJSX.CmPageTab & JSXBase.HTMLAttributes<HTMLCmPageTabElement>;
            "cm-page-tab-handle": LocalJSX.CmPageTabHandle & JSXBase.HTMLAttributes<HTMLCmPageTabHandleElement>;
            "cm-text": LocalJSX.CmText & JSXBase.HTMLAttributes<HTMLCmTextElement>;
        }
    }
}
